name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install --upgrade setuptools wheel twine bump2version

      - name: Auto-increment version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Run bump2version
          bump2version patch || echo "No version bump needed"

          # Only commit if there are changes
          if ! git diff --exit-code; then
            git commit -am "chore: new version"
            git push origin main
          else
            echo "No changes to commit."
          fi

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
